FROM docker.io/golang:1.25.4@sha256:e68f6a00e88586577fafa4d9cefad1349c2be70d21244321321c407474ff9bf2 AS builder
WORKDIR /app

ARG CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd

RUN go build -o ./build/main ./cmd/...

# ---

FROM docker.io/debian:13.2-slim@sha256:9812458f2932ede726468ba07bcb9e51bceb1f0c7f16ee30baa789ccee7cc202
WORKDIR /app

RUN apt update \
  && apt install -y --no-install-recommends curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-auto-merge-prs

COPY --from=builder /app/build/main /usr/local/bin/

CMD ["/usr/local/bin/main"]
