FROM docker.io/golang:1.25.3@sha256:6ea52a02734dd15e943286b048278da1e04eca196a564578d718c7720433dbbe AS builder
WORKDIR /app

ARG CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd

RUN go build -o ./build/main ./cmd/...

# ---

FROM docker.io/debian:13.1-slim@sha256:66b37a5078a77098bfc80175fb5eb881a3196809242fd295b25502854e12cbec
WORKDIR /app

RUN apt update \
  && apt install -y --no-install-recommends curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-auto-merge-prs

COPY --from=builder /app/build/main /usr/local/bin/

CMD ["/usr/local/bin/main"]
