FROM docker.io/golang:1.25.4@sha256:f60eaa87c79e604967c84d18fd3b151b3ee3f033bcdade4f3494e38411e60963 AS builder
WORKDIR /app

ARG CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd
COPY ./internal ./internal

RUN go build -o ./build/main ./cmd/...

# ---

FROM docker.io/debian:13.1-slim@sha256:a347fd7510ee31a84387619a492ad6c8eb0af2f2682b916ff3e643eb076f925a
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-generate-tasks-and-ci

COPY --from=builder /app/build/main /usr/local/bin/

CMD ["/usr/local/bin/main"]
