FROM docker.io/golang:1.25.3@sha256:bce1e7ec780444d85d041889e7a0e542b0be7b272a7f46a5fb947f0f484b9736 AS builder
WORKDIR /app

ARG CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd
COPY ./internal ./internal

RUN go build -o ./build/main ./cmd/...

# ---

FROM docker.io/debian:13.1-slim@sha256:66b37a5078a77098bfc80175fb5eb881a3196809242fd295b25502854e12cbec
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-generate-tasks-and-ci

COPY --from=builder /app/build/main /usr/local/bin/

CMD ["/usr/local/bin/main"]
