FROM docker.io/golang:1.26.0@sha256:c83e68f3ebb6943a2904fa66348867d108119890a2c6a2e6f07b38d0eb6c25c5 AS builder
WORKDIR /app

ARG CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd

RUN go build -o ./build/main ./cmd/...

# ---

FROM docker.io/debian:13.3-slim@sha256:1d3c811171a08a5adaa4a163fbafd96b61b87aa871bbc7aa15431ac275d3d430
WORKDIR /app

COPY --from=builder /app/build/main /usr/local/bin/

CMD ["/usr/local/bin/main"]

LABEL image.name=markormesher/tedium-chore-update-image-labels
LABEL image.registry=ghcr.io
LABEL org.opencontainers.image.description=""
LABEL org.opencontainers.image.documentation=""
LABEL org.opencontainers.image.title="tedium-chores"
LABEL org.opencontainers.image.url="https://github.com/markormesher/tedium-chores"
LABEL org.opencontainers.image.vendor=""
LABEL org.opencontainers.image.version=""
