FROM docker.io/golang:1.25.5@sha256:31c1e53dfc1cc2d269deec9c83f58729fa3c53dc9a576f6426109d1e319e9e9a AS builder
WORKDIR /app

ARG CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd

RUN go build -o ./build/main ./cmd/...

# ---

FROM docker.io/debian:13.2-slim@sha256:91e29de1e4e20f771e97d452c8fa6370716ca4044febbec4838366d459963801
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-update-image-labels

COPY --from=builder /app/build/main /usr/local/bin/

CMD ["/usr/local/bin/main"]
