FROM docker.io/debian:13.6-slim@sha256:020c0d20b9880058cbe785a9db107156c3c75c2ac944a6aa7ab59f2add76a7bd
WORKDIR /app

RUN apt update \
  && apt install -y --no-install-recommends curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY ./apply-branch-protection.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/apply-branch-protection.sh

CMD ["/usr/local/bin/apply-branch-protection.sh"]

LABEL image.name=markormesher/tedium-chore-apply-branch-protection
LABEL image.registry=ghcr.io
LABEL org.opencontainers.image.description=""
LABEL org.opencontainers.image.documentation=""
LABEL org.opencontainers.image.title="tedium-chores"
LABEL org.opencontainers.image.url=""
LABEL org.opencontainers.image.vendor=""
LABEL org.opencontainers.image.version=""
