FROM docker.io/debian:bookworm-slim@sha256:1209d8fd77def86ceb6663deef7956481cc6c14a25e1e64daec12c0ceffcc19d
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-apply-branch-protection

RUN apt update \
  && apt install -y --no-install-recommends curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY ./apply-branch-protection.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/apply-branch-protection.sh

CMD ["/usr/local/bin/apply-branch-protection.sh"]
