FROM docker.io/debian:13.1-slim@sha256:66b37a5078a77098bfc80175fb5eb881a3196809242fd295b25502854e12cbec
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-apply-branch-protection

RUN apt update \
  && apt install -y --no-install-recommends curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY ./apply-branch-protection.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/apply-branch-protection.sh

CMD ["/usr/local/bin/apply-branch-protection.sh"]
