version: 2.1

jobs:
  checkout:
    docker:
      - image: cimg/base:2024.12
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  fetch-task:
    docker:
      - image: ghcr.io/markormesher/task-fetcher:v0.4.1
    steps:
      - run:
          name: Fetch task binary
          command: cp /task .
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint-go:
    docker:
      - image: docker.io/golang:1.23.4
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint Go
          command: ./task lint-go

  img:
    docker:
      - image: cimg/base:2024.12
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push container image
          command: |
            echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
            ./task imgrefs
            ./task imgbuild
            ./task imgpush

  ci-all:
    docker:
      - image: cimg/base:2024.12
    steps:
      - run:
          command: echo "Done"

workflows:
  version: 2
  main:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
      - fetch-task:
          filters:
            tags:
              only: /.*/
      - lint-go:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - img:
          requires:
            - checkout
            - fetch-task
            - lint-go
          filters:
            tags:
              only: /.*/
      - ci-all:
          requires:
            - checkout
            - fetch-task
            - lint-go
            - img
          filters:
            tags:
              only: /.*/
