version: "2.1"
jobs:
  checkout:
    docker:
      - image: cimg/base:2024.12
    steps:
      - checkout:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - .
  ci-all:
    docker:
      - image: cimg/base:2024.12
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "Done"
  fetch-task:
    docker:
      - image: ghcr.io/markormesher/task-fetcher:v0.4.1
    steps:
      - attach_workspace:
          at: .
      - run:
          command: cp /task .
      - persist_to_workspace:
          root: .
          paths:
            - .
  imgbuild:
    docker:
      - image: cimg/base:2024.12
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: ./task imgbuild
  imgpush:
    docker:
      - image: cimg/base:2024.12
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: ./task imgpush
  imgrefs:
    docker:
      - image: docker.io/alpine/git:v2.47.1
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |-
            git fetch --tags
            ./task imgrefs
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint-go:
    docker:
      - image: docker.io/golang:1.23.4
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task lint-go
  test-go:
    docker:
      - image: docker.io/golang:1.23.4
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task test-go
workflows:
  version: 2
  main:
    jobs:
      - checkout:
          requires: []
      - fetch-task:
          requires:
            - checkout
      - lint-go:
          requires:
            - checkout
            - fetch-task
      - test-go:
          requires:
            - checkout
            - fetch-task
      - imgrefs:
          requires:
            - checkout
            - fetch-task
            - lint-go
            - test-go
      - imgbuild:
          requires:
            - checkout
            - fetch-task
            - imgrefs
            - lint-go
            - test-go
      - imgpush:
          requires:
            - checkout
            - fetch-task
            - imgbuild
            - imgrefs
            - lint-go
            - test-go
      - ci-all:
          requires:
            - checkout
            - fetch-task
            - imgbuild
            - imgpush
            - imgrefs
            - lint-go
            - test-go
