version: "2.1"
jobs:
  checkout:
    docker:
      - image: cimg/base:2024.12
    steps:
      - checkout:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - .
  ci-all:
    docker:
      - image: cimg/base:2024.12
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "Done"
  fetch-task:
    docker:
      - image: ghcr.io/markormesher/task-fetcher:v0.4.1
    steps:
      - attach_workspace:
          at: .
      - run:
          command: cp /task .
      - persist_to_workspace:
          root: .
          paths:
            - .
  imgbuild:
    docker:
      - image: cimg/base:2024.12
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: ./task imgbuild
  imgpush:
    docker:
      - image: cimg/base:2024.12
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: ./task imgpush
  imgrefs:
    docker:
      - image: docker.io/alpine/git:v2.47.1
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |-
            mkdir -p ~/.ssh
            echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> ~/.ssh/known_hosts
            echo "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=" >> ~/.ssh/known_hosts
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> ~/.ssh/known_hosts
            git fetch --tags
            ./task imgrefs
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint-go:
    docker:
      - image: docker.io/golang:1.23.4
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task lint-go
  test-go:
    docker:
      - image: docker.io/golang:1.23.4
    steps:
      - attach_workspace:
          at: .
      - run:
          command: ./task test-go
workflows:
  version: 2
  main:
    jobs:
      - checkout:
          requires: []
          filters:
            tags:
              only: /.*/
      - fetch-task:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/
      - lint-go:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - test-go:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
      - imgrefs:
          requires:
            - checkout
            - fetch-task
            - lint-go
            - test-go
          filters:
            tags:
              only: /.*/
      - imgbuild:
          requires:
            - checkout
            - fetch-task
            - imgrefs
            - lint-go
            - test-go
          filters:
            tags:
              only: /.*/
      - imgpush:
          requires:
            - checkout
            - fetch-task
            - imgbuild
            - imgrefs
            - lint-go
            - test-go
          filters:
            tags:
              only: /.*/
      - ci-all:
          requires:
            - checkout
            - fetch-task
            - imgbuild
            - imgpush
            - imgrefs
            - lint-go
            - test-go
          filters:
            tags:
              only: /.*/
