FROM docker.io/debian:13.2-slim@sha256:e711a7b30ec1261130d0a121050b4ed81d7fb28aeabcf4ea0c7876d4e9f5aca2
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-rewrite-debian-versions

COPY ./rewrite-debian-versions.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/rewrite-debian-versions.sh

CMD ["/usr/local/bin/rewrite-debian-versions.sh"]
