FROM docker.io/debian:13.0-slim@sha256:c85a2732e97694ea77237c61304b3bb410e0e961dd6ee945997a06c788c545bb
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-rewrite-debian-versions

COPY ./rewrite-debian-versions.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/rewrite-debian-versions.sh

CMD ["/usr/local/bin/rewrite-debian-versions.sh"]
