FROM docker.io/debian:13.6-slim@sha256:d7e12182ce18b85b93007c1dedf31f2d29e01ccf3182cc4017c709b6259bc132
WORKDIR /app

COPY ./set-go-toolchain.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/set-go-toolchain.sh

CMD ["/usr/local/bin/set-go-toolchain.sh"]

LABEL image.name=markormesher/tedium-chore-set-go-toolchain
LABEL image.registry=ghcr.io
LABEL org.opencontainers.image.description=""
LABEL org.opencontainers.image.documentation=""
LABEL org.opencontainers.image.title="tedium-chores"
LABEL org.opencontainers.image.url=""
LABEL org.opencontainers.image.vendor=""
LABEL org.opencontainers.image.version=""
