FROM docker.io/debian:13.7-slim@sha256:a29215f6a35e51e22adffa17f89e9d2ef06214e64a2bad10d765c46aea49f11f
WORKDIR /app

COPY ./set-go-toolchain.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/set-go-toolchain.sh

CMD ["/usr/local/bin/set-go-toolchain.sh"]

LABEL image.name=markormesher/tedium-chore-set-go-toolchain
LABEL image.registry=ghcr.io
LABEL org.opencontainers.image.description=""
LABEL org.opencontainers.image.documentation=""
LABEL org.opencontainers.image.title="tedium-chores"
LABEL org.opencontainers.image.url=""
LABEL org.opencontainers.image.vendor=""
LABEL org.opencontainers.image.version=""
