FROM docker.io/golang:1.26.3@sha256:2d6c80227255c3112a4d08e67ba98e58efd3846daf15d9d7d4c389565d881b1a
WORKDIR /app

RUN apt update \
  && apt install -y --no-install-recommends jq \
  && rm -rf /var/lib/apt/lists/*

COPY ./manage-go-tools.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/manage-go-tools.sh

CMD ["/usr/local/bin/manage-go-tools.sh"]

LABEL image.name=markormesher/tedium-chore-manage-go-tools
LABEL image.registry=ghcr.io
LABEL org.opencontainers.image.description=""
LABEL org.opencontainers.image.documentation=""
LABEL org.opencontainers.image.title="tedium-chores"
LABEL org.opencontainers.image.url="https://github.com/markormesher/tedium-chores"
LABEL org.opencontainers.image.vendor=""
LABEL org.opencontainers.image.version=""
