FROM docker.io/golang:1.25.0@sha256:4859242e2c392ddc9d3225fd41181c00a443d9cc005b8e5131ce164106fbc676
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-manage-go-tools

RUN apt update \
  && apt install -y --no-install-recommends jq \
  && rm -rf /var/lib/apt/lists/*

COPY ./manage-go-tools.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/manage-go-tools.sh

CMD ["/usr/local/bin/manage-go-tools.sh"]
