FROM docker.io/golang:1.25.1@sha256:8305f5fa8ea63c7b5bc85bd223ccc62941f852318ebfbd22f53bbd0b358c07e1
WORKDIR /app

LABEL image.registry=ghcr.io
LABEL image.name=markormesher/tedium-chore-manage-go-tools

RUN apt update \
  && apt install -y --no-install-recommends jq \
  && rm -rf /var/lib/apt/lists/*

COPY ./manage-go-tools.sh /usr/local/bin/.
RUN chmod +x /usr/local/bin/manage-go-tools.sh

CMD ["/usr/local/bin/manage-go-tools.sh"]
